---
- name: Install and Start the Service
  hosts: all
  become: true
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Starting the nginx service
    systemctl:
      name: nginx
      state: started
      enabled: true
      
    
      
