---
- name: File Module
  hosts: all
  become: true
  
  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: touch
      owner: root
      group: root
      mode: u=rwx,g=rw,o=r
      
