---
- name: firewall changes
  hosts: all
  become: true

  tasks:
  - name: installing the firewalld package
    yum:
      name: firewalld
      state: present
  - name: Enable a service in firewalld
    firewalld:
      service: nginx
      permanent: true
      state: enabled
  - name: reload the firewalld
    service:
      name: firewalld
      state: reloaded
