---
- name: create users using ansible loops
  hosts: all
  become: true
  vars:
   users:
    - name:
       akshita
       disha
       ruchit
       sangeeta
       sanjay
    - uid:
       101
       102
       103
  tasks:
  user:
     name: "{{ item.name }}"
     state: present
     shell: /bin/zsh
     uid: "{{item.uid}}"
  loop: "{{ users }}"
