---
- name: create users using ansible loops
  hosts: all
  become: true
  vars:
   users:
    - name: disha
      uid: 101
      password: "{{'disha23' | password_hash('sha512')}}"
    - name: akshita
      uid: 102
      password: "{{'akshita09' | password_hash('sha512')}}"
    - name: sangeeta
      uid: 103
      password: "{{'sangeeta23' | password_hash('sha512')}}"
    - name: sanjay
      uid: 104
      password: "{{'sanjay27' | password_hash('sha512')}}"
    - name: ruchit
      uid: 105
      password: "{{'ruchit14' | password_hash('sha512')}}"
  tasks:
   - name: add multiple users
     user:
      name: "{{ item.name }}"
      state: present
      shell: /bin/zsh
      uid: "{{ item.uid }}"
      password: "{{ item.password }}"
     loop: "{{ users }}"
