---
- name: create users using ansible loops
  hosts: all
  become: true
  vars:
   users:
    - name: disha
      uid: 101
    - name: akshita
      uid: 102
    - name: sangeeta
      uid: 103
    - name: sanjay
      uid: 104
    - name: ruchit
      uid: 105
  tasks:
  user:
     name: "{{ item.name }}"
     state: present
     shell: /bin/zsh
     uid: "{{ item.uid }}"
  loop: "{{ users }}"
