---
- name: create users using ansible loops
  hosts: all
  become: true
  vars:
   users:
      name: ["akshita", "disha", "ruchit", "sangeeta", "sanjay"]
      uid: [1, 2, 3]
  tasks:
  user:
     name: "{{ item.name }}"
     state: present
     shell: /bin/zsh
     uid: 10"{{item.uid}}"
  loop: "{{ users }}"
